version: "{build}"
branches:
  only:
  - dev
  - devops
  - master
skip_branch_with_pr: true

image: Visual Studio 2017
clone_folder: c:\SRC\control-center

environment:
  matrix:
  - QT: C:\Qt\5.10.1\msvc2017_64
    PLATFORM: amd64
    COMPILER: msvc
  decrypt_key:
    secure: Tltl7p3aLMTyXRsy3msl5g==

install:
  - set PATH=%PATH%;%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;
  - nuget install secure-file -ExcludeVersion
build_script:
  - C:\msys64\usr\bin\bash -lc "wget -nv -O /C/SRC/control-center/libs.tar.gz 'https://masterbazaar.subutai.io/rest/v1/cdn/raw?name=libs.tar.gz&latest&download' && tar -xf /C/SRC/control-center/libs.tar.gz -C /C/SRC/control-center"
  - cmd: build_win.bat
