version: "{build}"
branches:
  only:
  - dev
  - devops
  - master
skip_branch_with_pr: true

image: Visual Studio 2017
clone_folder: c:\SRC\control-center

environment:
  decrypt_key:
    secure: NBsr6b52BdT084Ca0vMPLbmP/mILkLvErsxw1k0YOrM=
  decrypt_salt:
    secure: VLUkq6lj7FP9R/QvSo5IKUPhFVonyJ45UOeUsbwxTD0QW0mz9wEkTsOc/YiWac+XrRdP7dYW7IOFbpcJJ7lU6w==
  matrix:
  - QT: C:\Qt\5.10.1\msvc2017_64
    PLATFORM: amd64
    COMPILER: msvc
    TOXENV: py36
    PYTHON: "C:\\Python36-x64"
    BASH: "C:\\msys64\\usr\\bin\\bash"

install:
  - set PATH=%PATH%;%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;
  - nuget install secure-file -ExcludeVersion
  - git clone https://github.com/subutai-io/devops.git C:\devops
  - C:\msys64\usr\bin\bash -lc "ls -l /C/devops"
  - cmd: secure-file\tools\secure-file -decrypt C:\devops\cc.tar.gz.enc -secret "%decrypt_key%" -salt "%decrypt_salt%"
  - C:\msys64\usr\bin\bash -lc "tar -xf /C/devops/cc.tar.gz -C /C/devops"
  - "%PYTHON%\\python.exe -m pip install requests python-gnupg subutai-bazaar"
build_script:
  - C:\msys64\usr\bin\bash -lc "wget -nv -O /C/SRC/control-center/libs.tar.gz 'https://masterbazaar.subutai.io/rest/v1/cdn/raw?name=libs.tar.gz&latest&download' && tar -xf /C/SRC/control-center/libs.tar.gz -C /C/SRC/control-center"
  - cmd: build_win.bat
deploy_script:
  - C:\msys64\usr\bin\bash -lc "cd /C/devops && gpg --allow-secret-key-import --import jenkins@subut.ai.gpg"
  - C:\msys64\usr\bin\bash -lc "cd /C/devops && gpg --allow-secret-key-import --import jenkins@optimal-dynamics.gpg"
  - C:\msys64\usr\bin\bash -lc "cd /C/devops && rm -f *.gpg"

