version: "{build}"
branches:
  only:
  - dev
  - devops
  - master
skip_branch_with_pr: true

image: Visual Studio 2017
clone_folder: c:\SRC\control-center

environment:
  decrypt_key:
    secure: NBsr6b52BdT084Ca0vMPLbmP/mILkLvErsxw1k0YOrM=
  decrypt_salt:
    secure: VLUkq6lj7FP9R/QvSo5IKUPhFVonyJ45UOeUsbwxTD0QW0mz9wEkTsOc/YiWac+XrRdP7dYW7IOFbpcJJ7lU6w==
  matrix:
  - QT: C:\Qt\5.10.1\msvc2017_64
    PLATFORM: amd64
    COMPILER: msvc
    TOXENV: py36
    PYTHON: "C:\\Python36-x64"

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - set PATH=%PATH%;%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;
    #  - nuget install secure-file
  - git clone https://github.com/subutai-io/devops.git C:\devops
  - cmd: appveyor-tools\secure-file -decrypt C:\devops\cc.tar.gz.enc -secret %decrypt_key% -salt %decrypt_salt% -out C:\devops\cc.tar.gz
  - C:\msys64\usr\bin\bash -lc "tar -xf /C/devops/cc.tar.gz -C /C/devops"
  - "%PYTHON%\\python.exe -m pip install requests python-gnupg subutai-bazaar"
build_script:
  - C:\msys64\usr\bin\bash -lc "wget -nv -O /C/SRC/control-center/libs.tar.gz 'https://masterbazaar.subutai.io/rest/v1/cdn/raw?name=libs.tar.gz&latest&download' && tar -xf /C/SRC/control-center/libs.tar.gz -C /C/SRC/control-center"
  - cmd: build_win.bat
deploy_script:
  - C:\msys64\usr\bin\bash -lc "ls -l /C/SRC/control-center"
  - C:\msys64\usr\bin\bash -lc "ls -l /C/SRC/control-center/subutai_control_center_bin"
  - C:\msys64\usr\bin\bash -lc "cp /C/SRC/control-center/subutai_control_center_bin/SubutaiControlCenter.exe /C/SRC/SubutaiControlCenter-devops.exe"
  - gpg.exe --allow-secret-key-import --import C:\devops\jenkins@subut.ai.gpg
  - gpg.exe --allow-secret-key-import --import C:\devops\jenkins@optimal-dynamics.com.gpg
    #  - C:\msys64\usr\bin\bash -lc "cd /C/devops && gpg --allow-secret-key-import --import jenkins@subut.ai.gpg"
    #  - C:\msys64\usr\bin\bash -lc "cd /C/devops && gpg --allow-secret-key-import --import jenkins@optimal-dynamics.com.gpg"
  - C:\msys64\usr\bin\bash -lc "cd /C/devops && rm -f *.gpg"
  - gpg.exe --list-keys
  - ps: |
      if ("$env:APPVEYOR_REPO_BRANCH" -eq "devops") {
        & "C:\Python36-x64\python.exe" "C:\devops\upload.py" "--user=jenkins@optimal-dynamics.com" "--fingerprint=877B586E74F170BC4CF6ECABB971E2AC63D23DC9" "--file=C:\SRC\SubutaiControlCenter-devops.exe"
      } elseif ("$env:APPVEYOR_REPO_BRANCH" -eq "dev") {
        Exec-External {& $env.PYTHON\python.exe C:\devops\upload.py --user=jenkins@optimal-dynamics.com --fingerprint=877B586E74F170BC4CF6ECABB971E2AC63D23DC9 --file=C:\SRC\SubutaiControlCenter-devops.exe}
      } elseif ("$env:APPVEYOR_REPO_BRANCH" -eq "master") {
        Exec-External {& $env.PYTHON\python.exe C:\devops\upload.py --user=jenkins@optimal-dynamics.com --fingerprint=877B586E74F170BC4CF6ECABB971E2AC63D23DC9 --file=C:\SRC\SubutaiControlCenter-devops.exe}
      }
    #  - "%PYTHON%\\python.exe C:\\devops\\upload.py --user=jenkins@optimal-dynamics.com --fingerprint=877B586E74F170BC4CF6ECABB971E2AC63D23DC9 --file=C:\\SRC\\SubutaiControlCenter-devops.exe"
    #  - "%PYTHON%\\python.exe C:\\devops\\upload.py --user=jenkins@optimal-dynamics.com --fingerprint=877B586E74F170BC4CF6ECABB971E2AC63D23DC9 --file=C:\\SRC\\control-center\\subutai_control_center_bin\\subutai-control-center-devops.msi"

